### ISSUE TITLE
Adabt new HFP sink solution for new use case

### ISSUE THREAD

**Issue by MinnaEmilia** [HSLdevcom/transitdata#157] opened 2021-09-24 12:26 UTC
Tarkempi määrittely tulee Teemulta.

**Comment by mjaakko** [comment] 2021-09-30 12:50
Is this duplicate of #156 ?

**Comment by teemu8655** [comment] 2021-10-05 07:41
Yes this is duplicate, closing this one

**Closed** 2021-10-05 07:41 UTC
