### ISSUE TITLE
Why google maps is missing real time data

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#168] opened 2021-10-05 10:15 UTC
No real time data in Google maps 2.10.2021 klo 17:32
![Image from iOS](https://user-images.githubusercontent.com/52199408/136004289-3096d90a-c6ff-40d1-b7ef-766cb242de9b.png)

Investigate why there was no data. We recieved no alerts from monitoring.

**Comment by mjaakko** [comment] 2021-11-18 13:55
It seems that the problem is on Google's side. Let's ask them about it.

**Comment by mjaakko** [comment] 2021-12-02 14:26
Waiting for response from Google

**Comment by mjaakko** [comment] 2022-03-23 10:06
Moving this back to backlog. Not high priority, because this issue seems to only appear occasionally. #195 would make debugging this easier.

**Closed** 2023-05-19 07:39 UTC
Labels: investigation task
